services:
  backend:
    image: ghcr.io/kin0-0ko/pl-jobhunter/backend:latest
    env_file: ./apps/backend/.env
    environment:
      - HOST=0.0.0.0
    volumes:
      - ./apps/backend/wallet:/app/apps/backend/wallet:ro
    restart: unless-stopped
